/* automatically generated by rust-bindgen 0.66.1 */

#[link(name = "sum")]

extern "C" {
  pub fn sum(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
  pub fn doubleSum(a: f64, b: f64) -> f64;
}
extern "C" {
  pub fn concatenateStrings(
    str1: *const ::std::os::raw::c_char,
    str2: *const ::std::os::raw::c_char,
  ) -> *const ::std::os::raw::c_char;
}
extern "C" {
  pub fn noRet();
}
extern "C" {
  pub fn createArrayi32(
    arr: *const ::std::os::raw::c_int,
    size: ::std::os::raw::c_int,
  ) -> *mut ::std::os::raw::c_int;
}
extern "C" {
  pub fn createArrayString(
    arr: *mut *const ::std::os::raw::c_char,
    size: ::std::os::raw::c_int,
  ) -> *mut *mut ::std::os::raw::c_char;
}
