/* automatically generated by rust-bindgen 0.66.0 */

extern "C" {
  pub fn sum(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
  pub fn concatenateStrings(
    str1: *const ::std::os::raw::c_char,
    str2: *const ::std::os::raw::c_char,
  ) -> *const ::std::os::raw::c_char;
}
